# Generated by Django 5.0.3 on 2024-03-28 20:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_testreport"),
    ]

    operations = [
        migrations.CreateModel(
            name="Doctor_Blog",
            fields=[
                ("sno", models.AutoField(primary_key=True, serialize=False)),
                ("name", models.CharField(max_length=255)),
                ("message", models.TextField()),
                ("specific", models.TextField()),
                ("image", models.ImageField(upload_to="image/")),
                ("time", models.DateTimeField(blank=True)),
                ("user_id", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Video",
            fields=[
                ("vno", models.AutoField(primary_key=True, serialize=False)),
                ("title", models.CharField(max_length=100)),
                ("video", models.FileField(upload_to="videos/")),
            ],
            options={
                "verbose_name": "video",
                "verbose_name_plural": "videos",
            },
        ),
    ]
