# Generated by Django 5.0.3 on 2024-08-23 13:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0008_alter_customuser_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="mobile_number",
        ),
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True, default=3, max_length=254, verbose_name="email address"
            ),
            preserve_default=False,
        ),
    ]
