# Generated by Django 5.0.3 on 2024-08-24 19:22

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0011_customuser_is_mobile_verified_customuser_otp"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="customuser",
            name="is_mobile_verified",
        ),
        migrations.RemoveField(
            model_name="customuser",
            name="otp",
        ),
    ]
